CREATE DATABASE TEST;

USE TEST;

SELECT * FROM EMPS;

SELECT * FROM EMPS WHERE DEPT = 'TEMP';

SELECT * FROM EMPS WHERE DEPT != 'TEMP';

SELECT * FROM EMPS WHERE DEPT <> 'TEMP';

SELECT * FROM EMPS WHERE SALARY > 300000;
SELECT * FROM EMPS WHERE SALARY >= 352508;

SELECT * FROM EMPS WHERE SALARY < 300000
ORDER BY SALARY ASC;

SELECT * FROM EMPS WHERE SALARY <= 245000;


-- AND, OR , NOT--OPERATOR--


SELECT * FROM EMPS WHERE DEPT = 'HR' AND DESI = 'MANAGER';

SELECT * FROM EMPS WHERE DEPT = 'ADMIN' OR DESI = 'ASSOCIATE';

SELECT * FROM EMPS WHERE NOT DEPT = 'MIS';

SELECT * FROM EMPS WHERE SALARY >= 300000 AND SALARY <=400000; --


-- RANGE--

SELECT * FROM EMPS WHERE SALARY BETWEEN 300000 AND 400000;

-- IS NULL--

SELECT * FROM EMPS WHERE SALARY IS NULL;

-- DISTINCT--

SELECT DISTINCT DEPT FROM EMPS;

SELECT DISTINCT DESI FROM EMPS;

SELECT  DESI FROM EMPS;











